name: Condition-events-workflow

on:
  pull_request:
    types: [closed]

jobs:
  condition-events-workflow:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Run condition events workflow
        run: echo "This workflow runs only when a pull request is merged."

